### ISSUE TITLE
Missing APIs for 8.4.0

### ISSUE THREAD

**Issue by mlocati** [concretecms/api#6]
It seems that the documentation for concrete5 version 8.4.0 is not yet present at https://documentation.concrete5.org/api

Is the generation of the API docs a manual process? If so, what about implementing the cron job [I suggested here](https://github.com/concrete5/api/pull/5#issue-161832918)?

**Comment by aembler** [comment]
Thanks, I have manually rebuilt the API docs. 

I like the cron idea, but we'll just add this to our list of things we need to do when we do a release.
